# I am a comment, and I want to say that the Variable CC will be the compiler to use.
CC=g++
# I am comment number 2. I want to say that CFLAGS will be the options I'll pass to the compiler
CFLAGS=-c -Wall

all:
	gcc -g main.c -o main
	gcc -g map.c -o map 
	gcc -g wc.c -o wc

clean:
	rm main map wc
